export { default as HeroSection } from './HeroSection'
export { default as Experience } from './Experience'
export { default as FeaturedProjects } from './FeaturedProjects'
export { default as FeaturedPosts } from './FeaturedPosts'
export { default as Socials } from './Socials'
export { default as Connect } from './Connect'
export { default as SocialsConnect } from './SocialsConnect'
